version: '3'
services:
  canebane:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      MONGODB_URI: "mongodb://mongodb:27017/canebane"
      JWT_SECRET: "bB&7!dK*8Tp^3zL%fY9Qw@X#ErCgGhVr2Mt=+Js"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
